### ISSUE TITLE
Linux Bug Report (Strlib)

### ISSUE THREAD

**Issue by ChaoticSomeone** [ChaoticSomeone/MySpace#7]
Dec2Bin causes a SegFault, when using SIGNMODE_SBIT or SIGNMODE_S2C

Windows works fine though

**Comment by Anurag1008** [comment]
can i work on this issue?

**Comment by ChaoticSomeone** [comment]
I don't mind it, so go ahead if you want to

**Comment by Anurag1008** [comment]
Thankyou for your response.

**Comment by Anurag1008** [comment]
My pleasure. Can you guide me where i can find some more issue?

**Comment by ChaoticSomeone** [comment]
I don't see a pull request in this repo, you might have opened it in your fork of the repo. As far as I'm aware, there are no more known bugs, but feel free to do some bug hunting yourself. Thanks for fixing the SegFault!

**Comment by Anurag1008** [comment]
![Screenshot 2023-05-26 180942](https://github.com/ChaoticSomeone/MySpace/assets/129081739/33955ab2-6d5a-40b5-b262-2b932181eee0)
I had already put a pull request.

**Comment by ChaoticSomeone** [comment]
Well yeah, but that pull request is inside of your fork of my repo, so not directly in my repo, thus I can neither merge nor see it.
![Screenshot 2023-05-26 145247](https://github.com/ChaoticSomeone/MySpace/assets/121238064/74eefdab-08cd-4047-a192-bcd61f2b272c)

**Comment by ChaoticSomeone** [comment]
Consider taking a look at the github docs:

[https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork](url)

**Comment by ChaoticSomeone** [comment]
Thanks for working on the issue!

**Comment by Anurag1008** [comment]
I am glad to meet and work with you.
